# Generated by Django 5.1.4 on 2024-12-13 12:56

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=30, null=True)),
                ('url_id', models.CharField(default=app.models.generate_unique_id, editable=False, max_length=8, unique=True)),
                ('content', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
